name: 'Build'
on: [ release, workflow_dispatch ]
env:
  FLUTTER_TARGET_VER: '3.7.x'
jobs:

  test:
    name: 'Unit tests & code analysis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{env.FLUTTER_TARGET_VER}}'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      # Use this commit till there is a new release that uses Node 16
      - uses: invertase/github-action-dart-analyzer@1cda5922c6369263b1c7e2fbe281f69704f4d63e
        with:
          fatal-infos: true
          fatal-warnings: true
      - run: flutter test

  ios:
    name: 'Build iOS app'
    needs: test
    if: '${{false}}' # disabled, as I'm to swabian to afford macOs CI
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '${{env.FLUTTER_TARGET_VER}}'
        channel: 'stable'
        architecture: x64
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v2
      with:
        name: ios-release
        path: build/ios/

  android:
    name: 'Build android app'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '${{env.FLUTTER_TARGET_VER}}'
        channel: 'stable'
        cache: true
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk     
    - uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/apk/release/app-release.apk
    
  web:
    name: 'Build web app'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{env.FLUTTER_TARGET_VER}}'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web --release  --base-href='/flutester/'
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/web/

  web_deploy:
    name: 'Deploy web app'
    needs: web
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1

